name: build on push

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: build project
        working-directory: ./
        run: |
          npm install
          npm run build

      - name: clone
        working-directory: ./dist
        run: |
          git clone https://github.com/demoshang/Auto.js.git
          ls -la ./

      - name: autojs replace inrt
        working-directory: ./dist
        run: |
          npx @s4p/autojs-replace-inrt "./Auto.js" "./all"
          cd "./Auto.js"
          git status

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        working-directory: ./dist/Auto.js
        run: chmod 777 ./gradlew && ./gradlew :inrt:assembleDebug && find inrt/build/outputs

      - name: Upload apk
        uses: actions/upload-artifact@v1
        with:
          name: autojs-debug
          path: dist/Auto.js/inrt/build/outputs/apk/debug/
